// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sated.Data;

#nullable disable

namespace Sated.Data.Migrations
{
    [DbContext(typeof(SatedDbContext))]
    [Migration("20260830122029_AddNutrientsToFoods")]
    partial class AddNutrientsToFoods
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sated.Data.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FdcId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Sated.Data.Entities.Food", b =>
                {
                    b.OwnsOne("Sated.Data.Entities.NutrientAmounts", "Nutrients", b1 =>
                        {
                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<double?>("Calcium")
                                .HasColumnType("double precision");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision");

                            b1.Property<double>("Fiber")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Iron")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Leucine")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Magnesium")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Potassium")
                                .HasColumnType("double precision");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision");

                            b1.Property<double>("SaturatedFat")
                                .HasColumnType("double precision");

                            b1.Property<double>("Sodium")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Thiamine")
                                .HasColumnType("double precision");

                            b1.Property<double?>("VitaminA")
                                .HasColumnType("double precision");

                            b1.Property<double?>("VitaminC")
                                .HasColumnType("double precision");

                            b1.Property<double?>("VitaminD")
                                .HasColumnType("double precision");

                            b1.Property<double?>("VitaminE")
                                .HasColumnType("double precision");

                            b1.HasKey("FoodId");

                            b1.ToTable("Foods");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.Navigation("Nutrients")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
