namespace Sated.Scoring;

/// <summary>
/// The leucine a food carries, for the case the catalogue could not supply it (FR-6).
/// </summary>
public static class ProteinCompleteness
{
    // Leucine as a share of protein, measured rather than borrowed: the median across the 2,286
    // FNDDS foods whose own recipes resolve into SR Legacy amino acid data, joined through the
    // ingredient codes each survey food carries (tools/LeucineJoinQuery).
    // It replaces an animal 8.8% / plant 7.1% split from Gorissen et al. 2018 and the twenty-five
    // category names that decided which half applied. Measured on this catalogue the two groups
    // sit 0.31 points apart — 7.59% against 7.28% — not the 1.7 the paper reports, and swapping
    // the split for this one number changes no letter in the benchmark's 138 rows.
    // A share, not an amount: it survives a food whose recipe only partly resolved. See P46.

    private const double LeucineShareOfProtein = 0.0752;

    // The same join, kept per category instead of collapsed to its median. The spread is what the
    // one number was hiding: boiled potato's category measures 6.02% and dairy 9.47%, against the
    // 7.52% both were given. P46 collapsed them because the animal/plant split it replaced was
    // only 0.31 points wide on this catalogue — but that was a statement about two groups, not
    // about the 125 categories underneath. Generated by tools/LeucineJoinQuery.
    private static readonly Dictionary<string, double> ShareByCategory = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Apples"] = 0.05882,
        ["Baby food: cereals"] = 0.07956,
        ["Baby food: meat and dinners"] = 0.08584,
        ["Baby food: snacks and sweets"] = 0.04725,
        ["Baby food: vegetables"] = 0.06500,
        ["Bacon"] = 0.08036,
        ["Bagels and English muffins"] = 0.06851,
        ["Bean, pea, legume dishes"] = 0.07187,
        ["Beans, peas, legumes"] = 0.07991,
        ["Beef, excludes ground"] = 0.08276,
        ["Biscuits, muffins, quick breads"] = 0.09061,
        ["Blueberries and other berries"] = 0.05949,
        ["Broccoli"] = 0.04626,
        ["Burgers"] = 0.07816,
        ["Burritos and tacos"] = 0.07144,
        ["Butter and animal fats"] = 0.08936,
        ["Cabbage"] = 0.03217,
        ["Cakes and pies"] = 0.07463,
        ["Candy containing chocolate"] = 0.06952,
        ["Candy not containing chocolate"] = 0.06560,
        ["Carrots"] = 0.10953,
        ["Cereal bars"] = 0.07168,
        ["Cheese"] = 0.09580,
        ["Cheese sandwiches"] = 0.08472,
        ["Chicken fillet sandwiches"] = 0.06233,
        ["Chicken patties, nuggets and tenders"] = 0.07449,
        ["Chicken, whole pieces"] = 0.08166,
        ["Citrus fruits"] = 0.02419,
        ["Citrus juice"] = 0.02014,
        ["Coffee"] = 0.04545,
        ["Cold cuts and cured meats"] = 0.07833,
        ["Cookies and brownies"] = 0.06800,
        ["Corn"] = 0.10642,
        ["Cottage/ricotta cheese"] = 0.10096,
        ["Crackers, excludes saltines"] = 0.06978,
        ["Cream and cream substitutes"] = 0.08243,
        ["Cream cheese, sour cream, whipped cream"] = 0.10795,
        ["Deli and cured meat sandwiches"] = 0.08199,
        ["Dips, gravies, other sauces"] = 0.08429,
        ["Doughnuts, sweet rolls, pastries"] = 0.07387,
        ["Dried fruits"] = 0.04453,
        ["Egg rolls, dumplings, sushi"] = 0.05076,
        ["Egg/breakfast sandwiches"] = 0.07414,
        ["Eggs and omelets"] = 0.08651,
        ["Fish"] = 0.08105,
        ["Frankfurter sandwiches"] = 0.07572,
        ["French fries and other fried white potatoes"] = 0.07434,
        ["Fried rice and lo/chow mein"] = 0.08272,
        ["Fruit drinks"] = 0.04845,
        ["Gelatins, ices, sorbets"] = 0.03197,
        ["Ground beef"] = 0.07789,
        ["Ice cream and frozen dairy desserts"] = 0.08897,
        ["Jams, syrups, toppings"] = 0.08997,
        ["Lamb, goat, game"] = 0.07902,
        ["Lettuce and lettuce salads"] = 0.05537,
        ["Liquor and cocktails"] = 0.05623,
        ["Liver and organ meats"] = 0.08955,
        ["Mango and papaya"] = 0.06098,
        ["Mashed potatoes and white potato mixtures"] = 0.08472,
        ["Mayonnaise"] = 0.08632,
        ["Meat mixed dishes"] = 0.07734,
        ["Melons"] = 0.03064,
        ["Milk shakes and other dairy drinks"] = 0.10034,
        ["Milk, nonfat"] = 0.09466,
        ["Milk, reduced fat"] = 0.09485,
        ["Milk, whole"] = 0.09492,
        ["Mustard and other condiments"] = 0.05273,
        ["Not included in a food category"] = 0.06804,
        ["Nutrition bars"] = 0.07760,
        ["Nuts and seeds"] = 0.06982,
        ["Oatmeal"] = 0.08067,
        ["Olives, pickles, pickled vegetables"] = 0.05200,
        ["Onions"] = 0.04739,
        ["Other dark green vegetables"] = 0.06973,
        ["Other fruit juice"] = 0.04159,
        ["Other fruits and fruit salads"] = 0.04400,
        ["Other Mexican mixed dishes"] = 0.08172,
        ["Other red and orange vegetables"] = 0.05152,
        ["Other starchy vegetables"] = 0.05959,
        ["Other vegetables and combinations"] = 0.05676,
        ["Pancakes, waffles, French toast"] = 0.08651,
        ["Pasta mixed dishes, excludes macaroni and cheese"] = 0.07483,
        ["Pasta sauces, tomato-based"] = 0.08429,
        ["Pasta, noodles, cooked grains"] = 0.06828,
        ["Peaches and nectarines"] = 0.02967,
        ["Peanut butter and jelly sandwiches"] = 0.06982,
        ["Pears"] = 0.04868,
        ["Pineapple"] = 0.04199,
        ["Pizza"] = 0.08199,
        ["Plant-based milk"] = 0.07424,
        ["Popcorn"] = 0.11395,
        ["Pork"] = 0.08217,
        ["Potato chips"] = 0.08092,
        ["Poultry mixed dishes"] = 0.08024,
        ["Pretzels/snack mix"] = 0.07238,
        ["Ramen and Asian broth-based soups"] = 0.06815,
        ["Ready-to-eat cereal, higher sugar (>21.2g/100g)"] = 0.08098,
        ["Ready-to-eat cereal, lower sugar (=<21.2g/100g)"] = 0.07704,
        ["Rice mixed dishes"] = 0.07978,
        ["Rolls and buns"] = 0.06886,
        ["Salad dressings and vegetable oils"] = 0.05610,
        ["Saltine crackers"] = 0.06892,
        ["Sausages"] = 0.07370,
        ["Seafood mixed dishes"] = 0.07973,
        ["Shellfish"] = 0.07318,
        ["Smoothies and grain drinks"] = 0.06239,
        ["Soups, broth-based"] = 0.07251,
        ["Soups, cream-based"] = 0.07805,
        ["Soy and meat-alternative products"] = 0.07436,
        ["Soy-based condiments"] = 0.06575,
        ["Spinach"] = 0.07794,
        ["Stir-fry and soy-based sauce mixtures"] = 0.07117,
        ["Strawberries"] = 0.05116,
        ["String beans"] = 0.06120,
        ["Tomatoes"] = 0.03129,
        ["Tortilla, corn, other chips"] = 0.11970,
        ["Tortillas"] = 0.07297,
        ["Turkey, duck, other poultry"] = 0.06944,
        ["Turnovers and other grain-based items"] = 0.07886,
        ["Vegetable dishes"] = 0.07707,
        ["Vegetable juice"] = 0.03577,
        ["Vegetable sandwiches/burgers"] = 0.06967,
        ["White potatoes, baked or boiled"] = 0.06020,
        ["Yeast breads"] = 0.06915,
        ["Yogurt, regular"] = 0.10081,
    };

    /// <returns>Grams of leucine per 100 g of food, estimated rather than measured.</returns>
    public static double EstimateLeucinePer100g(double proteinPer100g, string? category = null)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(proteinPer100g);

        var share = category is not null && ShareByCategory.TryGetValue(category, out var measured)
            ? measured
            : LeucineShareOfProtein;

        return proteinPer100g * share;
    }
}
