namespace Sated.Parsing;

internal static class CatalogueCategories
{
    public static readonly HashSet<string> Selected =
    [
        "Chicken, whole pieces",
        "Turkey, duck, other poultry",
        "Beef, excludes ground",
        "Ground beef",
        "Pork",
        "Lamb, goat, game",
        "Liver and organ meats",
        "Fish",
        "Shellfish",

        "Eggs and omelets",
        "Cheese",
        "Cottage/ricotta cheese",
        "Yogurt, regular",
        "Yogurt, Greek",
        "Milk, whole",
        "Milk, reduced fat",
        "Milk, lowfat",
        "Milk, nonfat",

        "Other vegetables and combinations",
        "Other dark green vegetables",
        "Other red and orange vegetables",
        "Other starchy vegetables",
        "White potatoes, baked or boiled",
        "Broccoli",
        "Spinach",
        "Cabbage",
        "Carrots",
        "Corn",
        "String beans",
        "Onions",
        "Tomatoes",
        "Lettuce and lettuce salads",

        "Other fruits and fruit salads",
        "Dried fruits",
        "Blueberries and other berries",
        "Citrus fruits",
        "Apples",
        "Bananas",
        "Grapes",
        "Melons",
        "Mango and papaya",
        "Peaches and nectarines",
        "Pears",
        "Pineapple",
        "Strawberries",

        "Beans, peas, legumes",
        "Nuts and seeds",
        "Rice",
        "Oatmeal",
        "Pasta, noodles, cooked grains",
        "Grits and other cooked cereals",

        "Butter and animal fats",
        "Salad dressings and vegetable oils",

        "Coffee",
        "Tea",
        "Soft drinks",
        "Diet soft drinks",
        "Fruit drinks",
        "Citrus juice",
        "Apple juice",
        "Other fruit juice",
        "Vegetable juice",
        "Plant-based milk",
        "Sport and energy drinks",
        "Diet sport and energy drinks",
        "Beer",
        "Wine",
        "Tap water",
        "Bottled water",
        "Flavored or carbonated water",
        "Enhanced water"
    ];
}
