using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

// Extracts the portion FNDDS itself calls typical, so D6 has data instead of an argument.
//
// A letter is a property of a food per 100 g and stays one: per portion the same olive oil would
// read one letter at 14 g and another at 100 g, and a food cannot have two letters. What the
// portion is for is the display beside the letter, and the ranking — a view that puts cocoa
// powder above salmon is comparing 5 g against 140 g and saying nothing.
//
// "Quantity not specified" is FNDDS's own default amount for a food, which is exactly the
// question being asked. It is not a guess of ours: 5,364 of 5,432 foods carry one.

var foods = JsonSerializer.Deserialize<SurveyFoodsFile>(
    File.ReadAllText("../UsdaCoverageQuery/data/surveyDownload.json"))!.Foods;

var rows = new List<(string FdcId, double Grams, string Source, string Description)>();
var missing = new List<string>();

foreach (var food in foods)
{
    var portions = food.FoodPortions ?? [];

    var own = portions.FirstOrDefault(portion =>
        portion.PortionDescription?.Contains("not specified", StringComparison.OrdinalIgnoreCase)
        == true && portion.GramWeight > 0);

    if (own is not null)
    {
        rows.Add((food.FdcId.ToString(), own.GramWeight, "stated", food.Description));
        continue;
    }

    // A food FNDDS gives no default amount for. The median of what it does list beats nothing,
    // and Source says which of the two a reader is looking at — a stand-in must never read as
    // the catalogue's own answer.
    var weights = portions.Where(p => p.GramWeight > 0).Select(p => p.GramWeight).Order().ToArray();

    if (weights.Length == 0)
    {
        missing.Add(food.Description);
        continue;
    }

    rows.Add((food.FdcId.ToString(), weights[weights.Length / 2], "median", food.Description));
}

var file = new StringBuilder();
file.AppendLine("# The portion FNDDS calls typical for each food, in grams. Generated by");
file.AppendLine("# tools/TypicalPortionQuery. Do not edit by hand.");
file.AppendLine("# Source: \"stated\" is the catalogue's own Quantity-not-specified amount;");
file.AppendLine("# \"median\" is the middle of the portions it does list, for foods with no default.");
file.AppendLine("# The grade is NOT computed on this. A letter is per 100 g and does not move with");
file.AppendLine("# how much was eaten (ComponentStrategy). This is what the product shows beside it.");
file.AppendLine("FdcId,Grams,Source,Description");

foreach (var row in rows.OrderBy(r => int.Parse(r.FdcId)))
{
    file.AppendLine($"{row.FdcId},{row.Grams.ToString(CultureInfo.InvariantCulture)}," +
        $"{row.Source},\"{row.Description.Replace("\"", "\"\"")}\"");
}

File.WriteAllText("typical-portions.csv", file.ToString());

var stated = rows.Count(r => r.Source == "stated");

Console.WriteLine($"Catalog: {foods.Length} alimente");
Console.WriteLine($"porție proprie FNDDS: {stated} · mediană: {rows.Count - stated} · " +
    $"fără nicio porție: {missing.Count}");
Console.WriteLine($"typical-portions.csv: {rows.Count} rânduri\n");

Console.WriteLine("Cât de departe de 100 g e o porție reală:");
foreach (var band in new[] { (0.0, 10.0), (10.0, 30.0), (30.0, 100.0), (100.0, 1e9) })
{
    var count = rows.Count(r => r.Grams >= band.Item1 && r.Grams < band.Item2);
    var label = band.Item2 > 1e8 ? "100 g și peste" : $"{band.Item1,3:F0}-{band.Item2,3:F0} g";
    Console.WriteLine($"  {label,-16} {count,5}  {100.0 * count / rows.Count,5:F1}%");
}

Console.WriteLine("\nAlimentele care au ridicat D6 — porția lor tipică:");
foreach (var needle in new[]
{
    "Nutritional powder mix, high protein (Slim Fast)", "Cocoa powder, not reconstituted",
    "Textured vegetable protein, dry", "Vegetable mixture, dried", "Seaweed, dried",
    "Fish, salmon, baked or broiled", "Broccoli, raw", "Olive oil"
})
{
    var match = rows.FirstOrDefault(r => r.Description == needle);
    Console.WriteLine(match.Description is null
        ? $"  {needle,-48} negăsit"
        : $"  {needle,-48} {match.Grams,6:F0} g");
}

public record Portion(
    [property: JsonPropertyName("portionDescription")] string? PortionDescription,
    [property: JsonPropertyName("gramWeight")] double GramWeight);
public record FoodItem(
    [property: JsonPropertyName("fdcId")] int FdcId,
    [property: JsonPropertyName("description")] string Description,
    [property: JsonPropertyName("foodPortions")] Portion[]? FoodPortions);
public record SurveyFoodsFile([property: JsonPropertyName("SurveyFoods")] FoodItem[] Foods);
